# Generated by Django 2.2.1 on 2019-05-31 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Site',
            fields=[
                ('site_id', models.IntegerField(primary_key=True, serialize=False)),
                ('site_name', models.CharField(default='', max_length=20)),
                ('site_description', models.CharField(default='', max_length=50)),
                ('site_x_cor', models.IntegerField(default='')),
                ('site_y_cor', models.IntegerField(default='')),
                ('site_fav_rate', models.IntegerField(default=0)),
            ],
        ),
    ]
