# Generated by Django 2.2.1 on 2019-05-26 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='category',
            field=models.IntegerField(choices=[(0, 'User'), (1, 'Staff'), (2, 'Admin')], default=0),
        ),
    ]
