# Generated by Django 2.2.1 on 2019-05-29 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0002_auto_20190526_0712'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='category',
        ),
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.IntegerField(choices=[(0, 'User'), (1, 'Staff'), (2, 'Dev'), (3, 'Admin')], default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='role_category',
            field=models.IntegerField(choices=[(0, 'Category1'), (1, 'Category2'), (2, 'Category3'), (3, 'Category4'), (4, 'Category5')], default=0),
        ),
    ]
