# Generated by Django 2.2.1 on 2019-05-26 05:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Station', '0001_initial'),
        ('Route', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RouteXStation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seq', models.IntegerField()),
                ('route', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Route.Route')),
                ('station', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Station.Station')),
            ],
        ),
    ]
