# Generated by Django 2.2.1 on 2019-05-31 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Combination', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserFav',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fav_sites', models.BinaryField(blank=True, null=True)),
                ('fav_routes', models.BinaryField(blank=True, null=True)),
                ('fav_stations', models.BinaryField(blank=True, null=True)),
            ],
        ),
    ]
