# Generated by Django 2.2.1 on 2019-05-29 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Flow',
            fields=[
                ('date_1', models.BinaryField(blank=True)),
                ('date_2', models.BinaryField(blank=True)),
                ('date_3', models.BinaryField(blank=True)),
                ('date_4', models.BinaryField(blank=True)),
                ('date_5', models.BinaryField(blank=True)),
                ('date_6', models.BinaryField(blank=True)),
                ('date_7', models.BinaryField(blank=True)),
                ('date_8', models.BinaryField(blank=True)),
                ('date_9', models.BinaryField(blank=True)),
                ('date_10', models.BinaryField(blank=True)),
                ('date_11', models.BinaryField(blank=True)),
                ('date_12', models.BinaryField(blank=True)),
                ('date_13', models.BinaryField(blank=True)),
                ('date_14', models.BinaryField(blank=True)),
                ('date_15', models.BinaryField(blank=True)),
                ('date_16', models.BinaryField(blank=True)),
                ('date_17', models.BinaryField(blank=True)),
                ('date_18', models.BinaryField(blank=True)),
                ('date_19', models.BinaryField(blank=True)),
                ('date_20', models.BinaryField(blank=True)),
                ('date_21', models.BinaryField(blank=True)),
                ('date_22', models.BinaryField(blank=True)),
                ('date_23', models.BinaryField(blank=True)),
                ('date_24', models.BinaryField(blank=True)),
                ('date_25', models.BinaryField(blank=True)),
                ('date_26', models.BinaryField(blank=True)),
                ('date_27', models.BinaryField(blank=True)),
                ('date_28', models.BinaryField(blank=True)),
                ('date_29', models.BinaryField(blank=True)),
                ('date_30', models.BinaryField(blank=True)),
                ('date_31', models.BinaryField(blank=True)),
                ('id', models.IntegerField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'flow',
            },
        ),
    ]
