# Generated by Django 2.2.1 on 2019-05-29 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Station',
            fields=[
                ('station_id', models.IntegerField(primary_key=True, serialize=False)),
                ('station_name', models.CharField(default='', max_length=20)),
                ('station_x_cor', models.IntegerField()),
                ('station_y_cor', models.IntegerField()),
            ],
            options={
                'permissions': (('can_view_station', 'Can View Station'), ('can_edit_station', 'Can Edit Station')),
            },
        ),
    ]
