# Generated by Django 2.2.1 on 2019-05-29 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Operation', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='operation',
            name='role_belong_to',
            field=models.CharField(default='3', max_length=4),
        ),
    ]
