# Generated by Django 2.2.1 on 2019-05-30 13:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Operation', '0003_auto_20190529_1107'),
    ]

    operations = [
        migrations.RenameField(
            model_name='operation',
            old_name='role_belong_to',
            new_name='role',
        ),
    ]
