# Generated by Django 2.2.1 on 2019-05-26 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Route',
            fields=[
                ('route_id', models.IntegerField(primary_key=True, serialize=False)),
                ('route_name', models.CharField(default='', max_length=20)),
            ],
            options={
                'permissions': (('can_view_route', 'Can View Route'), ('can_edit_route', 'Can Edit Route')),
            },
        ),
    ]
