# Generated by Django 2.2.1 on 2019-05-31 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Route', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='route',
            name='route_name',
            field=models.CharField(default='', max_length=20, unique=True),
        ),
    ]
